#!/bin/sh

# exit script on error
set -e

echo "Removing old build products"

# remove old stuff
rm -rf ndll
rm -rf project/obj

echo "Rebuilding native library"

# generate native libraries
lime rebuild ./project ios -clean

echo "Complete"
